//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Revit.Addin.RevitTooltip {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class RevitTooltip : global::System.Configuration.ApplicationSettingsBase, ICloneable
    {
        
        private static RevitTooltip defaultInstance = ((RevitTooltip)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RevitTooltip())));
        
        public static RevitTooltip Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("施工BIM数据-检测.xlsx")]
        public string SurveyFile {
            get {
                return ((string)(this["SurveyFile"]));
            }
            set {
                this["SurveyFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double AlertNumber {
            get {
                return ((double)(this["AlertNumber"]));
            }
            set {
                this["AlertNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double AlertNumberAdd {
            get {
                return ((double)(this["AlertNumberAdd"]));
            }
            set {
                this["AlertNumberAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("施工BIM数据-基础.xlsx")]
        public string FoundationFile {
            get {
                return ((string)(this["FoundationFile"]));
            }
            set {
                this["FoundationFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("施工BIM数据-地墙.xlsx")]
        public string UnderWallFile {
            get {
                return ((string)(this["UnderWallFile"]));
            }
            set {
                this["UnderWallFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.1.1.0")]
        public string DfServer {
            get {
                return ((string)(this["DfServer"]));
            }
            set {
                this["DfServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hzj")]
        public string DfDB {
            get {
                return ((string)(this["DfDB"]));
            }
            set {
                this["DfDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string DfUser {
            get {
                return ((string)(this["DfUser"]));
            }
            set {
                this["DfUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string DfPassword {
            get {
                return ((string)(this["DfPassword"]));
            }
            set {
                this["DfPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("utf8")]
        public string DfCharset {
            get {
                return ((string)(this["DfCharset"]));
            }
            set {
                this["DfCharset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string DfPort {
            get {
                return ((string)(this["DfPort"]));
            }
            set {
                this["DfPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\SqliteDBFile")]
        public string SqliteFilePath {
            get {
                return ((string)(this["SqliteFilePath"]));
            }
            set {
                this["SqliteFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SqliteDfFile.db")]
        public string SqliteFileName {
            get {
                return ((string)(this["SqliteFileName"]));
            }
            set {
                this["SqliteFileName"] = value;
            }
        }

        public object Clone()
        {
            RevitTooltip newOne = new RevitTooltip();
            newOne.SurveyFile = this.SurveyFile;
            newOne.AlertNumber = this.AlertNumber;
            newOne.AlertNumberAdd = this.AlertNumberAdd;
            newOne.FoundationFile = this.FoundationFile;
            newOne.UnderWallFile = this.UnderWallFile;
            newOne.DfServer = this.DfServer;
            newOne.DfDB = this.DfDB;
            newOne.DfPort = this.DfPort;
            newOne.DfUser = this.DfUser;
            newOne.DfCharset = this.DfCharset;
            newOne.DfPassword = this.DfPassword;
            newOne.SqliteFileName = this.SqliteFileName;
            newOne.SqliteFilePath = this.SqliteFilePath;
            return newOne;
        }
    }
}
