//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMRevitAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIMRevitAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 10 的本地化字符串。
        /// </summary>
        internal static string Alert_Sum {
            get {
                return ResourceManager.GetString("Alert_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string Alert_Value {
            get {
                return ResourceManager.GetString("Alert_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 root 的本地化字符串。
        /// </summary>
        internal static string Df_Pass {
            get {
                return ResourceManager.GetString("Df_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 root 的本地化字符串。
        /// </summary>
        internal static string Df_User {
            get {
                return ResourceManager.GetString("Df_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 utf8 的本地化字符串。
        /// </summary>
        internal static string Server_CharSet {
            get {
                return ResourceManager.GetString("Server_CharSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3306 的本地化字符串。
        /// </summary>
        internal static string Server_Port {
            get {
                return ResourceManager.GetString("Server_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hzj 的本地化字符串。
        /// </summary>
        internal static string String_ServerName {
            get {
                return ResourceManager.GetString("String_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 127.0.0.1 的本地化字符串。
        /// </summary>
        internal static string String_ServerPath {
            get {
                return ResourceManager.GetString("String_ServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 慧之建插件 的本地化字符串。
        /// </summary>
        internal static string String_TabName {
            get {
                return ResourceManager.GetString("String_TabName", resourceCulture);
            }
        }
    }
}
