//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.Addin.RevitTooltip {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class RevitTooltip : global::System.Configuration.ApplicationSettingsBase {
        
        //private static RevitTooltip defaultInstance = ((RevitTooltip)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RevitTooltip())));
        
        public static RevitTooltip Default {
            get {
                return new RevitTooltip();
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.1.1.0")]
        public string DfServer {
            get {
                return ((string)(this["DfServer"]));
            }
            set {
                this["DfServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hzj")]
        public string DfDB {
            get {
                return ((string)(this["DfDB"]));
            }
            set {
                this["DfDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string DfUser {
            get {
                return ((string)(this["DfUser"]));
            }
            set {
                this["DfUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string DfPassword {
            get {
                return ((string)(this["DfPassword"]));
            }
            set {
                this["DfPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("utf8")]
        public string DfCharset {
            get {
                return ((string)(this["DfCharset"]));
            }
            set {
                this["DfCharset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string DfPort {
            get {
                return ((string)(this["DfPort"]));
            }
            set {
                this["DfPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\SqliteDBFile")]
        public string SqliteFilePath {
            get {
                return ((string)(this["SqliteFilePath"]));
            }
            set {
                this["SqliteFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SqliteDfFile.db")]
        public string SqliteFileName {
            get {
                return ((string)(this["SqliteFileName"]));
            }
            set {
                this["SqliteFileName"] = value;
            }
        }

        public override bool Equals(object obj)
        {
            RevitTooltip o = (RevitTooltip)obj;
            return this.DfCharset.Equals(o.DfCharset) &&
                this.DfDB.Equals(o.DfDB) &&
                this.DfPassword.Equals(o.DfPassword) &&
                this.DfPort.Equals(o.DfPort) &&
                this.DfServer.Equals(o.DfServer) &&
                this.DfUser.Equals(o.DfUser) &&
                this.SqliteFilePath.Equals(o.SqliteFilePath) &&
                this.SqliteFileName.Equals(o.SqliteFileName);
        }
        public override int GetHashCode()
        {
            return (this.DfCharset + this.DfDB + this.DfPassword + this.DfPort + this.DfServer + this.DfUser + this.SqliteFileName + this.SqliteFilePath).GetHashCode();
        }
    }
}
