//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.Addin.RevitTooltip.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Revit.Addin.RevitTooltip.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon about_16 {
            get {
                object obj = ResourceManager.GetObject("about_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 检测信息 的本地化字符串。
        /// </summary>
        internal static string Command_ElementInfo {
            get {
                return ResourceManager.GetString("Command_ElementInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新本地数据 的本地化字符串。
        /// </summary>
        internal static string Command_ReloadExcelData {
            get {
                return ResourceManager.GetString("Command_ReloadExcelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绘折线图 的本地化字符串。
        /// </summary>
        internal static string Command_SurveyImageInfo {
            get {
                return ResourceManager.GetString("Command_SurveyImageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About this application: copyrights, author, vendor and support contact. 的本地化字符串。
        /// </summary>
        internal static string CommandDescription_About {
            get {
                return ResourceManager.GetString("CommandDescription_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开构件信息检测面板 的本地化字符串。
        /// </summary>
        internal static string CommandDescription_ElementInfo {
            get {
                return ResourceManager.GetString("CommandDescription_ElementInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View help, to see the user manual of the application. 的本地化字符串。
        /// </summary>
        internal static string CommandDescription_Help {
            get {
                return ResourceManager.GetString("CommandDescription_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入数据到Mysql数据库 的本地化字符串。
        /// </summary>
        internal static string CommandDescription_Import {
            get {
                return ResourceManager.GetString("CommandDescription_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入excel表到本地数据库 的本地化字符串。
        /// </summary>
        internal static string CommandDescription_Import_SQLite {
            get {
                return ResourceManager.GetString("CommandDescription_Import_SQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To view the license information of the application. 的本地化字符串。
        /// </summary>
        internal static string CommandDescription_LicenseInfo {
            get {
                return ResourceManager.GetString("CommandDescription_LicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新加载Excel数据 的本地化字符串。
        /// </summary>
        internal static string CommandDescription_ReloadExcelData {
            get {
                return ResourceManager.GetString("CommandDescription_ReloadExcelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这顶监测时的相关数据，如导入监测数据及指定预警数值等。 的本地化字符串。
        /// </summary>
        internal static string CommandDescription_Settings {
            get {
                return ResourceManager.GetString("CommandDescription_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击，弹出绘制折线图的对话框 的本地化字符串。
        /// </summary>
        internal static string CommandDescription_SurveyImage {
            get {
                return ResourceManager.GetString("CommandDescription_SurveyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不显示提示框 的本地化字符串。
        /// </summary>
        internal static string CommandDescription_TooltipOff {
            get {
                return ResourceManager.GetString("CommandDescription_TooltipOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开属性面板，点击选取元素时自动显示元素相关属性 的本地化字符串。
        /// </summary>
        internal static string CommandDescription_TooltipOn {
            get {
                return ResourceManager.GetString("CommandDescription_TooltipOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string CommandName_About {
            get {
                return ResourceManager.GetString("CommandName_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string CommandName_Help {
            get {
                return ResourceManager.GetString("CommandName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入数据 的本地化字符串。
        /// </summary>
        internal static string CommandName_Import {
            get {
                return ResourceManager.GetString("CommandName_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入至本地 的本地化字符串。
        /// </summary>
        internal static string CommandName_Import_SQLite {
            get {
                return ResourceManager.GetString("CommandName_Import_SQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权信息 的本地化字符串。
        /// </summary>
        internal static string CommandName_LicenseInfo {
            get {
                return ResourceManager.GetString("CommandName_LicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监测设置 的本地化字符串。
        /// </summary>
        internal static string CommandName_Settings {
            get {
                return ResourceManager.GetString("CommandName_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏提示框 的本地化字符串。
        /// </summary>
        internal static string CommandName_TooltipOff {
            get {
                return ResourceManager.GetString("CommandName_TooltipOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示提示框 的本地化字符串。
        /// </summary>
        internal static string CommandName_TooltipOn {
            get {
                return ResourceManager.GetString("CommandName_TooltipOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 600 的本地化字符串。
        /// </summary>
        internal static string Double_Df_Radius {
            get {
                return ResourceManager.GetString("Double_Df_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string ExcelColumnHeader_Comment {
            get {
                return ResourceManager.GetString("ExcelColumnHeader_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon help_16 {
            get {
                object obj = ResourceManager.GetObject("help_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon license_16 {
            get {
                object obj = ResourceManager.GetObject("license_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 安全监测智能提示框 的本地化字符串。
        /// </summary>
        internal static string String_AppPanelName {
            get {
                return ResourceManager.GetString("String_AppPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全监测 的本地化字符串。
        /// </summary>
        internal static string String_AppTabName {
            get {
                return ResourceManager.GetString("String_AppTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        internal static string String_Color {
            get {
                return ResourceManager.GetString("String_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灰色 的本地化字符串。
        /// </summary>
        internal static string String_Color_Gray {
            get {
                return ResourceManager.GetString("String_Color_Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 红线 的本地化字符串。
        /// </summary>
        internal static string String_Color_Red {
            get {
                return ResourceManager.GetString("String_Color_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测点编号 的本地化字符串。
        /// </summary>
        internal static string String_ParameterName {
            get {
                return ResourceManager.GetString("String_ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测点 的本地化字符串。
        /// </summary>
        internal static string String_ParameterSurveyType {
            get {
                return ResourceManager.GetString("String_ParameterSurveyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 墙类型 的本地化字符串。
        /// </summary>
        internal static string String_ParameterWallTypeName {
            get {
                return ResourceManager.GetString("String_ParameterWallTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半径 的本地化字符串。
        /// </summary>
        internal static string String_Radius {
            get {
                return ResourceManager.GetString("String_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CX 的本地化字符串。
        /// </summary>
        internal static string String_Reg {
            get {
                return ResourceManager.GetString("String_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要导入的监测数据 的本地化字符串。
        /// </summary>
        internal static string String_SelectExcelFile {
            get {
                return ResourceManager.GetString("String_SelectExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地下连续墙 的本地化字符串。
        /// </summary>
        internal static string String_UnderWallName {
            get {
                return ResourceManager.GetString("String_UnderWallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Tooltip_64 {
            get {
                object obj = ResourceManager.GetObject("Tooltip_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon tooltip_off {
            get {
                object obj = ResourceManager.GetObject("tooltip_off", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon tooltip_on {
            get {
                object obj = ResourceManager.GetObject("tooltip_on", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
